WebAnimalPassport/Models/Data/Event/Event.cs
using System.ComponentModel.DataAnnotations;

namespace WebAnimalPassport.Models.Data.Event
{
    public sealed class Event : EventBase
    {
        [Key]
        public long Id { get; set; }
        public CustomUser User { get; set; }
        public string? PhotoPath { get; set; }
        public List<CustomUser> CustomUsers { get; set; }

        public Event() : base() { }
        public Event(EventBase model) : base(model) { }
    }
}

WebAnimalPassport/Models/Data/Event/EventBase.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebAnimalPassport.Models.Data.Event
{
    public abstract class EventBase
    {
        [DisplayName("Название")]
        [Required(ErrorMessage = "Укажите название мероприятия!")]
        [MaxLength(1000, ErrorMessage = "Максимальная длина - 1000 символов!")]
        public string Name { get; set; }

        [DisplayName("Описание")]
        [Required(ErrorMessage = "Напишите краткое описание мероприятия!")]
        [MaxLength(1000, ErrorMessage = "Максимальная длина - 1000 символов!")]
        public string Description { get; set; }

        [DisplayName("Дата начала")]
        [Required(ErrorMessage = "Укажите дату!")]
        public DateTime DateStart { get; set; }

        [DisplayName("Дата конца")]
        [Required(ErrorMessage = "Укажите дату!")]
        public DateTime DateFinish { get; set; }

        public EventBase() : base() { }
        public EventBase(EventBase model) : this()
        {
            Name = model.Name;
            Description = model.Description;
            DateStart = model.DateStart;
            DateFinish = model.DateFinish;
        }

        public void Update(EventBase model)
        {
            Name = model.Name;
            Description = model.Description;
            DateStart = model.DateStart;
            DateFinish = model.DateFinish;
        }
    }
}

WebAnimalPassport/Models/View/Event/EventCreateModel.cs
using System.ComponentModel;
using WebAnimalPassport.Models.Data.Animal;
using WebAnimalPassport.Models.Data.Event;

namespace WebAnimalPassport.Models.View.Event
{
    public class EventCreateModel : EventBase
    {
        [DisplayName("Банер мероприятия")]
        public IFormFile? File { get; set; }

        public EventCreateModel() : base() { }
        public EventCreateModel(EventBase model) : base(model) { }
    }
}

WebAnimalPassport/Models/View/Event/EventEditModel.cs
namespace WebAnimalPassport.Models.View.Event
{
    public class EventEditModel : EventCreateModel
    {
        public long Id { get; set; }

        public EventEditModel() : base() { }
        public EventEditModel(Data.Event.Event model) : base(model)
        {
            Id = model.Id;
        }
    }
}

WebAnimalPassport/Controllers/EventController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebAnimalPassport.Data;
using WebAnimalPassport.Models.Data;
using WebAnimalPassport.Models.Data.Event;
using WebAnimalPassport.Models.View.Event;

namespace WebEventPassport.Controllers
{
    public class EventController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<CustomUser> _userManager;
        private readonly IWebHostEnvironment _env;
        public EventController(ApplicationDbContext context, UserManager<CustomUser> userManager, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
            _userManager = userManager;
        }

        #region List
        public async Task<IActionResult> List(string sortOrder, string searchString)
        {
            string? userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return Forbid();
            }

            ViewData["DateSortParm"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";

            var list = _context.Events
                .Include(x => x.User)
                .AsQueryable();

            if (!String.IsNullOrEmpty(searchString))
            {
                list = list.Where(v => v.Name.Contains(searchString) || v.DateStart.ToString().Contains(searchString) || v.DateFinish.ToString().Contains(searchString));
            }

            switch (sortOrder)
            {
                case "date_desc":
                    list = list.OrderByDescending(v => v.DateStart).ThenBy(v => v.DateFinish).ThenBy(v => v.Id);
                    break;
                default:
                    list = list.OrderBy(v => v.DateStart).ThenBy(v => v.DateFinish).ThenBy(v => v.Id);
                    break;
            }

            return View(await list.ToListAsync());
        }
        #endregion

        #region Index
        public async Task<IActionResult> Index(long id)
        {
            Event? found = await _context.Events
                .Include(x => x.User)
                .FirstOrDefaultAsync(x => x.Id == id);
            if (found == null)
            {
                return NotFound();
            }
            return View(found);
        }
        #endregion

        #region Create
        public IActionResult Create()
        {
            string? userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return Forbid();
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EventCreateModel model)
        {
            CustomUser? user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Forbid();
            }
            Event eventEv = new Event(model);
            eventEv.User = user;
            if (model.File != null)
            {
                Guid guid = Guid.NewGuid();
                string extension = Path.GetExtension(model.File.FileName);
                string completePath = $"{_env.WebRootPath}/src/Events/{guid}{extension}";
                while (System.IO.File.Exists(completePath))
                {
                    guid = Guid.NewGuid();
                    completePath = $"{_env.WebRootPath}/src/Events/{guid}{extension}";
                }
                try
                {
                    using (FileStream createStream = new FileStream(completePath, FileMode.Create))
                    {
                        await model.File.CopyToAsync(createStream);
                    }
                }
                catch
                {
                    ModelState.AddModelError("File", "Ошибка загрузки файла!");
                }
                eventEv.PhotoPath = $"{guid}{extension}";
            }
            if (ModelState.ErrorCount > 0)
            {
                return View(model);
            }
            await _context.Events.AddAsync(eventEv);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { eventEv.Id });
        }
        #endregion

        #region Edit
        public async Task<IActionResult> Edit(long id)
        {
            string? userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return Forbid();
            }
            Event? found = await _context.Events
                .Include(x => x.User)
                .FirstOrDefaultAsync(x => x.Id == id);
            if (found == null)
            {
                return NotFound();
            }
            if (found.User.Id != userId)
            {
                return Forbid();
            }
            EventEditModel model = new EventEditModel(found);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EventEditModel model)
        {
            string? userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return Forbid();
            }
            Event? found = await _context.Events
                .Include(x => x.User)
                .FirstOrDefaultAsync(x => x.Id == model.Id);
            if (found == null)
            {
                return NotFound();
            }
            if (found.User.Id != userId)
            {
                return Forbid();
            }
            if (model.File != null)
            {
                Guid guid = Guid.NewGuid();
                string extension = Path.GetExtension(model.File.FileName);
                string completePath = $"{_env.WebRootPath}/src/Events/{guid}{extension}";
                while (System.IO.File.Exists(completePath))
                {
                    guid = Guid.NewGuid();
                    completePath = $"{_env.WebRootPath}/src/Events/{guid}{extension}";
                }
                try
                {
                    using (FileStream createStream = new FileStream(completePath, FileMode.Create))
                    {
                        await model.File.CopyToAsync(createStream);
                    }
                    if (found.PhotoPath != null && System.IO.File.Exists($"{_env.WebRootPath}/src/Events/{found.PhotoPath}"))
                    {
                        System.IO.File.Delete($"{_env.WebRootPath}/src/Events/{found.PhotoPath}");
                    }
                }
                catch
                {
                    ModelState.AddModelError("File", "Ошибка загрузки файла!");
                }
                found.PhotoPath = $"{guid}{extension}";
            }
            if (ModelState.ErrorCount > 0)
            {
                return View(model);
            }

            Event eventEv = new Event(model);
            found.Update(eventEv);
            _context.Events.Update(found);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { found.Id });
        }
        #endregion
    }
}

WebAnimalPassport/Views/Event/Create.cshtml
@model EventCreateModel
@{
    ViewData["Title"] = "Создание нового мероприятия";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<form method="post" enctype='multipart/form-data'>
    <partial name="_EventModifyModel" />
    <div class="row">
        <div class="col-6">
            <a role="button" class="btn btn-dark w-100" asp-controller="Event" asp-action="List">Назад</a>
        </div>
        <div class="col-6">
            <button type="submit" class="btn btn-success w-100">Создать</button>
        </div>
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

WebAnimalPassport/Views/Event/Edit.cshtml
@model EventEditModel
@{
    ViewData["Title"] = "Изменение данных о мероприятии";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<form method="post" enctype='multipart/form-data'>
    <input asp-for="Id" hidden>
    <partial name="_EventModifyModel" />
    <div class="row">
        <div class="col-6">
            <a role="button" class="btn btn-dark w-100" asp-controller="Event" asp-action="Index" asp-route-id="@Model.Id">Назад</a>
        </div>
        <div class="col-6">
            <button type="submit" class="btn btn-dark w-100"> Изменить</button>
        </div>
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

WebAnimalPassport/Views/Event/Index.cshtml
@inject UserManager<CustomUser> UserManager

@model Event
@{
    ViewData["Title"] = Model.Name;
    bool canModify = await UserManager.GetUserAsync(User) == Model.User;
}
<h1 class="text-center">@ViewData["Title"]</h1>
<hr>

<div class="row">
    <div class="row justify-content-around">
        <div class="col-12 col-lg-3">
            @if (Model.PhotoPath != null)
            {
                <img class="rounded-custom w-100" src="~/src/Events/@Model.PhotoPath">
            }
            else
            {
                <img class="rounded-custom w-100" src="~/src/Stocks/NoImage.png">
            }
        </div>
        <div class="col-12 col-sm-4">
            <h5>Название - Name</h5>
            <p>@Model.Name</p>
            <h5>Организатор - Organizer</h5>
            <p>@Model.User.Surname @Model.User.Name @Model.User.Patronymic</p>
            @if (Model.User.PhoneNumber != null)
            {
                <h5>Телефон - Phone</h5>
                <p>@Model.User.PhoneNumber</p>
            }
            @if (Model.User.Email != null)
            {
                <h5>Почта - Email</h5>
                <p>@Model.User.Email</p>
            }
            <h5>Даты проведения - Dates</h5>
            <p>@Model.DateStart.ToString("D") - @Model.DateFinish.ToString("D")</p>
            <h5>Место проведения - Location</h5>
            <p>Улица Пушкина, дом 69</p>
        </div>
        <div class="col-12 col-sm-4">
            <h5>Описание - Description</h5>
            <p>@Model.Description</p>
        </div>
    </div>
</div>

@if (canModify)
{
    <hr class="mt-2">
    <a class="btn btn-warning w-100" asp-controller="Event" asp-action="Edit" asp-route-id="@Model.Id">Редатировать</a>
}

WebAnimalPassport/Views/Event/List.cshtml
@inject SignInManager<CustomUser> SignInManager
@inject UserManager<CustomUser> UserManager

@model List<Event>
@{
    ViewData["Title"] = "Мероприятия";
    string userId = UserManager.GetUserId(User);
    List<Event> actual = Model.Where(x => x.DateFinish >= DateTime.Today).ToList();
}

<div class="row mt-3 pb-2">
    <div class="col-3 text-center">
        <h1 class="text-center mt-4"><a asp-action="List" asp-route-sortOrder="@ViewData["DateSortParm"]" class="link link-dark page-link">@ViewData["Title"]</a></h1>
    </div>
    <div class="col-9">
        <form asp-action="List" method="get">
            <div class="form-actions no-color">
                <p class="mt-5">
                    <strong class="w-100 pb-1" style="font-size: 1.1rem">Поиск:</strong>
                    <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" class="w-50" />
                    <button type="submit" class="btn btn-primary"><i class="bi bi-search"></i></button>
                </p>
            </div>
        </form>
    </div>
</div>
<hr>
<div class="d-flex justify-content-center">
    <a class="btn btn-outline-success btn-lg w-75" asp-controller="Event" asp-action="Create">Объявить о мероприятии</a>
</div>
<table class="table table-hover w-100 mt-3 pb-2 cell-centered">
    <tbody class="cell-centered mt-5">
        @foreach (var eventEv in actual)
        {
            <tr>
                <td class="text-center">
                    <h5>@eventEv.Name</h5>
                    @if (eventEv.DateStart <= DateTime.Today && eventEv.DateFinish >= DateTime.Today)
                    {
                        if (eventEv.DateStart == eventEv.DateFinish)
                        {
                            <h5 class="text-success">Дата: @eventEv.DateFinish.ToString("D")</h5>
                        }
                        else
                        {
                            <h5 class="text-success">Дата: @eventEv.DateStart.ToString("D") - @eventEv.DateFinish.ToString("D")</h5>
                        }
                        <h5 style="color: lightgray">идёт сейчас</h5>
                    }
                    else
                    {
                        if (eventEv.DateStart == eventEv.DateFinish)
                        {
                            <h5>Дата: @eventEv.DateFinish.ToString("D")</h5>
                        }
                        else
                        {
                            <h5>Дата: @eventEv.DateStart.ToString("D") - @eventEv.DateFinish.ToString("D")</h5>
                        }
                    }
                </td>
                <td class="w-25">
                    <a class="btn p-0 border-0 rounded-2 btn-outline-success mt-auto" asp-controller="Event" asp-action="Index" asp-route-id="@eventEv.Id">
                        @if (eventEv.PhotoPath == null)
                        {
                            <img class="rounded-2 w-100 h-100" src="~/src/Stocks/NoImage.png">
                        }
                        else
                        {
                            <img class="rounded-2 w-100 h-100" src="~/src/Events/@eventEv.PhotoPath">
                        }
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>