WebAnimalPassport/Models/Data/Animal/Animal.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebAnimalPassport.Models.Data.Animal
{
    public sealed class Animal : AnimalBase
    {
        [Key]
        public long Id { get; set; }
        public CustomUser InitialUser { get; set; }
        public CustomUser User { get; set; }
        [DisplayName("Дата смерти")]
        public DateTime? DeathDate { get; set; }
        public string? PhotoPath { get; set; }
        public List<OwnerHistory> Owners { get; set; }
        public List<Note.Note> Notes { get; set; }
        public List<Vaccination.Vaccination> Vaccinations { get; set; }
        public List<Treatment.Treatment> Treatments { get; set; }
        public List<Examination.Examination> Examinations { get; set; }

        public Animal() : base() { }
        public Animal(AnimalBase model) : base(model) { }
    }
}

WebAnimalPassport/Models/Data/Animal/AnimalBase.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using WebAnimalPassport.Models.Enums;

namespace WebAnimalPassport.Models.Data.Animal
{
    public abstract class AnimalBase
    {
        [DisplayName("Кличка")]
        [Required(ErrorMessage = "Укажите кличку!")]
        [MaxLength(1000, ErrorMessage = "Максимальная длина - 1000 символов!")]
        public string Name { get; set; }
        [DisplayName("Порода")]
        [Required(ErrorMessage = "Укажите породу!")]
        [MaxLength(1000, ErrorMessage = "Максимальная длина - 1000 символов!")]
        public string Breed { get; set; }
        [DisplayName("Пол")]
        [Required(ErrorMessage = "Укажите пол!")]
        [Range(0,2, ErrorMessage = "Укажите пол!")]
        public Sex Sex { get; set; }
        [DisplayName("Вид")]
        [Required(ErrorMessage = "Укажите вид!")]
        public AnimalType Type { get; set; }
        [DisplayName("Шерсть")]
        [Required(ErrorMessage = "Укажите описание шерсти (например: окрас)!")]
        [MaxLength(1000, ErrorMessage = "Максимальная длина - 1000 символов!")]
        public string Hair { get; set; }
        [DisplayName("Номер микрочипа")]
        [MaxLength(1000, ErrorMessage = "Максимальная длина - 1000 символов!")]
        public string? ChipNumber { get; set; }
        [DisplayName("Дата чипирования")]
        public DateTime? ChipDate { get; set; }
        [DisplayName("Расположение микрочипа")]
        [MaxLength(1000, ErrorMessage = "Максимальная длина - 1000 символов!")]
        public string? ChipLocation { get; set; }
        [DisplayName("Клеймо")]
        [MaxLength(1000, ErrorMessage = "Максимальная длина - 1000 символов!")]
        public string? TattoNumber { get; set; }
        [DisplayName("Дата клеймления")]
        public DateTime? TattoDate { get; set; }
        [DisplayName("Дата рождения")]
        [Required(ErrorMessage = "Укажите дату рождения!")]
        public DateTime BirthDate { get; set; }
        public string? LostLocation { get; set; }

        public AnimalBase() : base() { }
        public AnimalBase(AnimalBase model) : this()
        {
            Name = model.Name;
            Type = model.Type;
            BirthDate = model.BirthDate;
            Breed = model.Breed;
            Sex = model.Sex;
            Hair = model.Hair;
            ChipNumber = model.ChipNumber;
            ChipDate = model.ChipDate;
            ChipLocation = model.ChipLocation;
            TattoNumber = model.TattoNumber;
            TattoDate = model.TattoDate;
        }

        public void Update(AnimalBase model)
        {
            Name = model.Name;
            BirthDate = model.BirthDate;
            Type = model.Type;
            Breed = model.Breed;
            Sex = model.Sex;
            Hair = model.Hair;
            ChipNumber = model.ChipNumber;
            ChipDate = model.ChipDate;
            ChipLocation = model.ChipLocation;
            TattoNumber = model.TattoNumber;
            TattoDate = model.TattoDate;
        }
    }
}

WebAnimalPassport/Models/Enums/AnimalType.cs
using System.ComponentModel.DataAnnotations;

namespace WebAnimalPassport.Models.Enums
{
    public enum AnimalType
    {
        [Display(Name = "Кошка")]
        Cat,
        [Display(Name = "Собака")]
        Dog
    }
}

WebAnimalPassport/Models/View/Animal/AnimalCreateModel.cs
using System.ComponentModel;
using WebAnimalPassport.Models.Data.Animal;

namespace WebAnimalPassport.Models.View.Animal
{
    public class AnimalCreateModel : AnimalBase
    {
        [DisplayName("Фото питомца (необязательно)")]
        public IFormFile? File { get; set; }

        public AnimalCreateModel() : base() { }
        public AnimalCreateModel(AnimalBase model) : base(model) { }
    }
}

WebAnimalPassport/Models/View/Animal/AnimalDeathModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebAnimalPassport.Models.View.Animal
{
    public sealed class AnimalDeathModel
    {
        public long AnimalId { get; set; }
        [ValidateNever]
        [DisplayName("Кличка")]
        public string AnimalName { get; set; }
        [DisplayName("Дата смерти")]
        [Required(ErrorMessage = "Укажите дату смерти!")]
        [ValidateNever]
        public DateTime Date { get; set; }
    }
}

WebAnimalPassport/Models/View/Animal/AnimalEditModel.cs
namespace WebAnimalPassport.Models.View.Animal
{
    public sealed class AnimalEditModel : AnimalCreateModel
    {
        public long Id { get; set; }

        public AnimalEditModel() : base() { }
        public AnimalEditModel(Data.Animal.Animal model) : base(model)
        {
            Id = model.Id;
        }
    }
}

WebAnimalPassport/Models/View/Animal/AnimalFoundModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;

namespace WebAnimalPassport.Models.View.Animal
{
    public sealed class AnimalFoundModel
    {
        public long AnimalId { get; set; }
        [DisplayName("Кличка питомца")]
        [ValidateNever]
        public string AnimalName { get; set; }
    }
}

WebAnimalPassport/Models/View/Animal/AnimalLostModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebAnimalPassport.Models.View.Animal
{
    public sealed class AnimalLostModel
    {
        public long AnimalId { get; set; }
        [DisplayName("Кличка питомца")]
        [ValidateNever]
        public string AnimalName { get; set; }
        [DisplayName("Адрес потери")]
        [Required(ErrorMessage = "Укажите адрес потери!")]
        public string Location { get; set; }
    }
}

WebAnimalPassport/Models/View/Animal/AnimalTransmitModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebAnimalPassport.Models.View.Animal
{
    public sealed class AnimalTransmitModel
    {
        public long AnimalId { get; set; }
        [DisplayName("Кличка питомца")]
        [ValidateNever]
        public string AnimalName { get; set; }
        [DisplayName("Идентификатор переноса другого пользователя")]
        [Required(ErrorMessage = "Укажите идентификатор другого пользователя!")]
        public string OtherUserId { get; set; }
        [DisplayName("Причина")]
        [Required(ErrorMessage = "Укажите причину!")]
        public string Reason { get; set; }
    }
}

WebAnimalPassport/Controllers/AnimalController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebAnimalPassport.Data;
using WebAnimalPassport.Models.Data;
using WebAnimalPassport.Models.Data.Animal;
using WebAnimalPassport.Models.View.Animal;

namespace WebAnimalPassport.Controllers
{
    public sealed class AnimalController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<CustomUser> _userManager;
        private readonly IWebHostEnvironment _env;
        public AnimalController(ApplicationDbContext context, UserManager<CustomUser> userManager, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
            _userManager = userManager;
        }

        #region List
        public async Task<IActionResult> List()
        {
            string? userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return Forbid();
            }
            List<Animal> list = await _context.Animals
                .Include(x => x.User)
                .Include(x => x.Owners)
                .ThenInclude(x=>x.User)
                .Where(x => x.User.Id == userId || x.Owners.Any(x=>x.User.Id == userId))
                .ToListAsync();
            return View(list);
        }
        #endregion

        #region ListLost
        public async Task<IActionResult> ListLost()
        {
            List<Animal> list = await _context.Animals.Where(x=>x.LostLocation != null && x.DeathDate == null).ToListAsync();
            return View(list);
        }
        #endregion

        #region Index
        public async Task<IActionResult> Index(long id)
        {
            Animal? found = await _context.Animals
                .Include(x => x.User)
                .Include(x => x.Notes)
                .Include(x => x.Owners.OrderBy(x=>x.TransmitDate))
                .Include(x => x.Vaccinations.OrderBy(x => x.StartDate))
                .ThenInclude(x => x.Doctor)
                .Include(x => x.Treatments.OrderBy(x => x.DateTime))
                .ThenInclude(x => x.Doctor)
                .Include(x => x.Examinations)
                .ThenInclude(x => x.Doctor)
                .Include(x => x.InitialUser)
                .FirstOrDefaultAsync(x => x.Id == id);
            if (found == null)
            {
                return NotFound();
            }
            return View(found);
        }
        #endregion

        #region Create
        public IActionResult Create()
        {
            string? userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return Forbid();
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AnimalCreateModel model)
        {
            CustomUser? user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Forbid();
            }
            Animal animal = new Animal(model);
            animal.User = user;
            animal.InitialUser = user;
            if (model.File != null)
            {
                Guid guid = Guid.NewGuid();
                string extension = Path.GetExtension(model.File.FileName);
                string completePath = $"{_env.WebRootPath}/src/Animals/{guid}{extension}";
                while (System.IO.File.Exists(completePath))
                {
                    guid = Guid.NewGuid();
                    completePath = $"{_env.WebRootPath}/src/Animals/{guid}{extension}";
                }
                try
                {
                    using (FileStream createStream = new FileStream(completePath, FileMode.Create))
                    {
                        await model.File.CopyToAsync(createStream);
                    }
                }
                catch
                {
                    ModelState.AddModelError("File", "Ошибка загрузки файла!");
                }
                animal.PhotoPath = $"{guid}{extension}";
            }
            if (ModelState.ErrorCount > 0)
            {
                return View(model);
            }
            await _context.Animals.AddAsync(animal);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { animal.Id });
        }
        #endregion

        #region Edit
        public async Task<IActionResult> Edit(long id)
        {
            string? userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return Forbid();
            }
            Animal? found = await _context.Animals
                .Include(x => x.User)
                .FirstOrDefaultAsync(x => x.Id == id);
            if (found == null)
            {
                return NotFound();
            }
            if (found.User.Id != userId)
            {
                return Forbid();
            }
            AnimalEditModel model = new AnimalEditModel(found);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AnimalEditModel model)
        {
            string? userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return Forbid();
            }
            Animal? found = await _context.Animals
                .Include(x => x.User)
                .Include(x => x.InitialUser)
                .FirstOrDefaultAsync(x => x.Id == model.Id);
            if (found == null)
            {
                return NotFound();
            }
            if (found.User.Id != userId)
            {
                return Forbid();
            }
            if (model.File != null)
            {
                Guid guid = Guid.NewGuid();
                string extension = Path.GetExtension(model.File.FileName);
                string completePath = $"{_env.WebRootPath}/src/Animals/{guid}{extension}";
                while (System.IO.File.Exists(completePath))
                {
                    guid = Guid.NewGuid();
                    completePath = $"{_env.WebRootPath}/src/Animals/{guid}{extension}";
                }
                try
                {
                    using (FileStream createStream = new FileStream(completePath, FileMode.Create))
                    {
                        await model.File.CopyToAsync(createStream);
                    }
                    if (found.PhotoPath != null && System.IO.File.Exists($"{_env.WebRootPath}/src/Animals/{found.PhotoPath}"))
                    {
                        System.IO.File.Delete($"{_env.WebRootPath}/src/Animals/{found.PhotoPath}");
                    }
                }
                catch
                {
                    ModelState.AddModelError("File", "Ошибка загрузки файла!");
                }
                found.PhotoPath = $"{guid}{extension}";
            }
            if (ModelState.ErrorCount > 0)
            {
                return View(model);
            }

            Animal animal = new Animal(model);
            found.Update(animal);
            _context.Animals.Update(found);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { found.Id });
        }
        #endregion

        #region Transmit
        public async Task<IActionResult> Transmit(long id)
        {
            string? userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return Forbid();
            }
            Animal? found = await _context.Animals
                .Include(x => x.User)
                .FirstOrDefaultAsync(x => x.Id == id);
            if (found == null)
            {
                return NotFound();
            }
            if (found.User.Id != userId)
            {
                return Forbid();
            }
            AnimalTransmitModel model = new AnimalTransmitModel()
            {
                AnimalId = id,
                AnimalName = found.Name,
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Transmit(AnimalTransmitModel model)
        {
            string? userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                return Forbid();
            }
            CustomUser? user = await _context.Users.FirstOrDefaultAsync(x => x.Id == model.OtherUserId);
            if (user == null)
            {
                ModelState.AddModelError("OtherUserId", "Пользотель с этим Id не найден!");
            }
            Animal? found = await _context.Animals
                .Include(x => x.User)
                .Include(x => x.InitialUser)
                .FirstOrDefaultAsync(x => x.Id == model.AnimalId);
            if (found == null)
            {
                return NotFound();
            }
            if (found.User.Id != userId)
            {
                return Forbid();
            }
            if (ModelState.ErrorCount > 0)
            {
                model.AnimalName = found.Name;
                return View(model);
            }
            OwnerHistory history = new OwnerHistory()
            {
                Animal = found,
                User = found.User,
                Reason = model.Reason,
                TransmitDate = DateTime.Now,
            };
            found.User = user;
            _context.Animals.Update(found);
            await _context.History.AddAsync(history);
            await _context.SaveChangesAsync();
            return RedirectToAction("List");
        }
        #endregion

        #region Death
        public async Task<IActionResult> Death(long id)
        {
            string? userId = _userManager.GetUserId(User);
            if (userId == null)
            {

WebAnimalPassport/Views/Animal/Create.cshtml
@model AnimalCreateModel
@{
    ViewData["Title"] = "Создание электронного паспорта питомца";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<form method="post" enctype='multipart/form-data'>
    <partial name="_AnimalModifyModel" />
    <div class="row">
        <div class="col-6">
            <a role="button" class="btn btn-dark w-100" asp-controller="Animal" asp-action="List">Назад</a>
        </div>
        <div class="col-6">
            <button type="submit" class="btn btn-success w-100">Создать</button>
        </div>
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

WebAnimalPassport/Views/Animal/Death.cshtml
@model AnimalDeathModel
@{
    ViewData["Title"] = "Фиксация смерти животного 😢";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<form method="post">
    <input asp-for="AnimalId" hidden>
    <div class="mb-1">
        <label asp-for="AnimalName" class="form-label"></label>
        <input asp-for="AnimalName" class="form-control" disabled>
    </div>
    <div class="mb-1">
        <label asp-for="Date" class="form-label"></label>
        <input asp-for="Date" type="date" class="form-control">
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>
    <div class="row">
        <div class="col-6">
            <a role="button" class="btn btn-dark w-100" asp-controller="Animal" asp-action="Index" asp-route-id="@Model.AnimalId">Назад</a>
        </div>
        <div class="col-6">
            <button type="submit" class="btn btn-danger w-100">Подтвердить</button>
        </div>
    </div>
</form>

WebAnimalPassport/Views/Animal/Edit.cshtml
@model AnimalEditModel
@{
    ViewData["Title"] = "Изменение данных паспорта питомца";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<form method="post" enctype='multipart/form-data'>
    <input asp-for="Id" hidden>
    <partial name="_AnimalModifyModel" />
    <div class="row">
        <div class="col-6">
            <a role="button" class="btn btn-dark w-100" asp-controller="Animal" asp-action="Index" asp-route-id="@Model.Id">Назад</a>
        </div>
        <div class="col-6">
            <button type="submit" class="btn btn-dark w-100"> Изменить</button>
        </div>
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

WebAnimalPassport/Views/Animal/Found.cshtml
@model AnimalFoundModel
@{
    ViewData["Title"] = "Объявить питомца найденным";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<form method="post">
    <input asp-for="AnimalId" hidden>
    <div class="mb-1">
        <label asp-for="AnimalName" class="form-label"></label>
        <input asp-for="AnimalName" class="form-control" disabled>
    </div>
    <div class="row">
        <div class="col-6">
            <a role="button" class="btn btn-dark w-100" asp-controller="Animal" asp-action="Index" asp-route-id="@Model.AnimalId">Назад</a>
        </div>
        <div class="col-6">
            <button type="submit" class="btn btn-success w-100">Подтвердить</button>
        </div>
    </div>
</form>

WebAnimalPassport/Views/Animal/List.cshtml
@inject SignInManager<CustomUser> SignInManager
@inject UserManager<CustomUser> UserManager

@model List<Animal>
@{
    ViewData["Title"] = "Ваши питомцы";
    string userId = UserManager.GetUserId(User);
    List<Animal> actual = Model.Where(x => x.DeathDate == null && x.User.Id == userId).ToList();
    List<Animal> old = Model.Where(x => x.Owners.Any(x => x.User.Id == userId) && x.DeathDate == null).ToList();
}
<h1 class="text-center">@ViewData["Title"]</h1>
<hr>

<div class="row">
    @foreach (Animal animal in actual)
    {
        <div class="col-12 col-sm-6 col-md-3 col-lg-2">
            <div class="card rounded-custom h-100">
                <a class="btn p-0 border-0 rounded-custom btn-outline-success mt-auto" asp-controller="Animal" asp-action="Index" asp-route-id="@animal.Id">
                    @if (animal.PhotoPath == null)
                    {
                        @switch (animal.Type)
                        {
                            case AnimalType.Cat:
                                <img class="rounded-custom w-100 h-100" src="~/src/Stocks/cat.svg">
                                break;
                            case AnimalType.Dog:
                                <img class="rounded-custom w-100 h-100" src="~/src/Stocks/dog.svg">
                                break;
                        }
                    }
                    else
                    {
                        <img class="rounded-custom w-100 h-100" src="~/src/Animals/@animal.PhotoPath">
                    }
                </a>
                <h3 class="text-center mt-auto">@animal.Name</h3>
                @if (animal.LostLocation != null)
                {
                    <h3 class="text-center text-danger">Пропавший</h3>
                }
            </div>
        </div>
    }
    <div class="col-12 col-sm-6 col-md-3 col-lg-2">
        @if (Model.Count == 0)
        {
            <a class="btn btn-outline-success h-100 w-100 d-flex align-items-center justify-content-center" style="height:234px !important;" asp-controller="Animal" asp-action="Create">Добавить питомца</a>
        }
        else
        {
            <a class="btn btn-outline-success h-100 w-100 d-flex align-items-center justify-content-center" asp-controller="Animal" asp-action="Create">Добавить питомца</a>
        }
    </div>
</div>
@if (old.Count != 0)
{
    <h2>Бывшие питомцы</h2>
    <div class="row">
        @foreach (Animal animal in old)
        {
            <div class="col-12 col-sm-6 col-md-3 col-lg-2">
                <div class="card rounded-custom h-100">
                    <a class="btn p-0 border-0 rounded-custom btn-outline-success mt-auto" asp-controller="Animal" asp-action="Index" asp-route-id="@animal.Id">
                        @if (animal.PhotoPath == null)
                        {
                            @switch (animal.Type)
                            {
                                case AnimalType.Cat:
                                    <img class="rounded-custom w-100 h-100" src="~/src/Stocks/cat.svg">
                                    break;
                                case AnimalType.Dog:
                                    <img class="rounded-custom w-100 h-100" src="~/src/Stocks/dog.svg">
                                    break;
                            }
                        }
                        else
                        {
                            <img class="rounded-custom w-100 h-100" src="~/src/Animals/@animal.PhotoPath">
                        }
                    </a>
                    <h3 class="text-center mt-auto">@animal.Name</h3>
                </div>
            </div>
        }
    </div>
}

WebAnimalPassport/Views/Animal/ListLost.cshtml
@model List<Animal>
@{
    ViewData["Title"] = "Список потерянных животных";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<div class="row">
    @if (Model.Count == 0)
    {
        <div class="col-12">
            <p class="text-center display-5">К счастью такие не найдены :)</p>
        </div>
    }
    @foreach (Animal animal in Model)
    {
        <div class="col-12 col-sm-6 col-md-3 col-lg-2">
            <div class="card rounded-custom h-100">
                <a class="btn p-0 border-0 rounded-custom btn-outline-success mt-auto" asp-controller="Animal" asp-action="Index" asp-route-id="@animal.Id">
                    @if (animal.PhotoPath == null)
                    {
                        @switch (animal.Type)
                        {
                            case AnimalType.Cat:
                                <img class="rounded-custom w-100 h-100" src="~/src/Stocks/cat.svg">
                                break;
                            case AnimalType.Dog:
                                <img class="rounded-custom w-100 h-100" src="~/src/Stocks/dog.svg">
                                break;
                        }
                    }
                    else
                    {
                        <img class="rounded-custom w-100 h-100" src="~/src/Animals/@animal.PhotoPath">
                    }
                </a>
                <h3 class="text-center mt-auto">@animal.Name</h3>
            </div>
        </div>
    }
</div>

WebAnimalPassport/Views/Animal/Lost.cshtml
@model AnimalLostModel
@{
    ViewData["Title"] = "Заявить о пропаже";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<form method="post">
    <input asp-for="AnimalId" hidden>
    <div class="mb-1">
        <label asp-for="AnimalName" class="form-label"></label>
        <input asp-for="AnimalName" class="form-control" disabled>
    </div>
    <div class="mb-1">
        <label asp-for="Location" class="form-label"></label>
        <textarea asp-for="Location" class="form-control" rows="5"></textarea>
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>
    <div class="row">
        <div class="col-6">
            <a role="button" class="btn btn-dark w-100" asp-controller="Animal" asp-action="Index" asp-route-id="@Model.AnimalId">Назад</a>
        </div>
        <div class="col-6">
            <button type="submit" class="btn btn-danger w-100">Подтвердить</button>
        </div>
    </div>
</form>

WebAnimalPassport/Views/Animal/Transmit.cshtml
@model AnimalTransmitModel
@{
    ViewData["Title"] = "Передача питомца";
}
<h1 class="text-center">@ViewData["Title"]</h1>
<form method="post">
    <input asp-for="AnimalId" hidden>
    <div class="mb-1">
        <label asp-for="AnimalName" class="form-label"></label>
        <input asp-for="AnimalName" class="form-control" disabled>
    </div>
    <div class="mb-1">
        <label asp-for="OtherUserId" class="form-label"></label>
        <input asp-for="OtherUserId" class="form-control">
        <span asp-validation-for="OtherUserId" class="text-danger"></span>
    </div>
    <div class="mb-1">
        <label asp-for="Reason" class="form-label"></label>
        <textarea asp-for="Reason" class="form-control" rows="5"></textarea>
        <span asp-validation-for="Reason" class="text-danger"></span>
    </div>
    <div class="row">
        <div class="col-6">
            <a role="button" class="btn btn-dark w-100" asp-controller="Animal" asp-action="Index" asp-route-id="@Model.AnimalId">Назад</a>
        </div>
        <div class="col-6">
            <button type="submit" class="btn btn-danger w-100">Передать</button>
        </div>
    </div>
</form>